version: '2'

services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: mos
      POSTGRES_PASSWORD: mos
      POSTGRES_DB: mos
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbit:
    image: rabbitmq:latest

  redis:
    image: redis:latest

  backend:
    build: ./submodules/mos-backend/
    restart: on-failure
    container_name: mos-backend
    environment:
      - MOS_BACKEND_DEBUG=1
      - MOS_BACKEND_HOST=0.0.0.0
      - MOS_BACKEND_PORT=8000
      - MOS_ADMIN_USR=mos
      - MOS_ADMIN_PWD=demo
      - MOS_ADMIN_EMAIL=some@email.net
      - MOS_DATABASE_NAME=mos
      - MOS_DATABASE_USR=mos
      - MOS_DATABASE_PWD=mos
      - MOS_DATABASE_HOST=db
      - MOS_RABBIT_PORT=5672  
      - MOS_RABBIT_USR=guest
      - MOS_RABBIT_PWD=guest
      - MOS_RABBIT_HOST=rabbit
      - MOS_REDIS_DB=0
      - MOS_REDIS_PORT=6379
      - MOS_REDIS_HOST=redis
      - MOS_DATABASE_PORT=5432
      - MOS_FRONTEND_HOST=localhost
      - MOS_FRONTEND_PORT=4200
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
    volumes:
      - django_data:/mos-backend

  frontend:
    build: ./submodules/mos-frontend/
    restart: on-failure
    container_name: mos-frontend
    ports:
      - "4200:4200"
    links:
      - backend
    depends_on:
      - backend

  compute-py:
    build: 
      context: ./submodules/mos-compute/
      dockerfile: Dockerfile-py
    restart: on-failure
    container_name: mos-compute-py
    environment:
      - MOS_BACKEND_HOST=localhost
      - MOS_BACKEND_PORT=8000
      - MOS_ADMIN_USR=mos
      - MOS_ADMIN_PWD=demo
      - MOS_RABBIT_PORT=5672
      - MOS_RABBIT_USR=guest
      - MOS_RABBIT_PWD=guest
      - MOS_RABBIT_HOST=rabbit
    links:
      - backend
    depends_on:
      - backend
      - rabbit
      - redis

volumes:
  postgres_data:
  django_data: